### ISSUE TITLE
[Issue] plugin breaks after adding universal

### ISSUE THREAD

**Issue by Jokerz97** [GC-spigot/Tokens#126]
[07:48:50 INFO]: [Tokens] Enabling Tokens v3.0.0
[07:48:50 INFO]: [Tokens] Registered AutoSell hook.
[07:48:50 INFO]: [PlaceholderAPI] Successfully registered expansion: tokens [3.0.0]
[07:48:50 ERROR]: Error occurred while enabling Tokens v3.0.0 (Is it up to date?)
java.lang.NoSuchFieldError: PLAYER_INTERACT
        at com.solodevelopment.universalenchant.UniversalEnchant.load(UniversalEnchant.java:231) ~[?:?]
        at com.solodevelopment.tokens.Tokens.loadEnchantments(Tokens.java:258) ~[?:?]
        at com.solodevelopment.tokens.Tokens.onEnable(Tokens.java:101) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version 3.0.0

**Comment by GlitchedFolx** [comment]
Doesn't work on 1.18.2 either, I think it needs an update.
