### ISSUE TITLE
[Issue] Token menu wont load.

### ISSUE THREAD

**Issue by ItzSave** [GC-spigot/Tokens#82]
**Describe the bug**
Tokens menu wont open and puts an error in console

**Server Information (please complete the following information):**
 - PaperSpigot 1.12.2 (Last Version)
- 2.9.8 (Bug does not occur on 2.9.7

**To Reproduce**
Use tokens on any paper spigot server running 1.12.2 install Effiencey enchantment and type /tokens menu

**Error**
```[15:43:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'tokens menu' in com.solodevelopment.tokens.commands.BaseCommand(tokens)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.solodevelopment.tokens.menu.inventory.MenuInventory@2aa45d67 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:541) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.solodevelopment.tokens.menu.api.ComplexPage.setInterval(ComplexPage.java:108) ~[?:?]
        at com.solodevelopment.tokens.menu.inventory.MenuInventory.<init>(MenuInventory.java:28) ~[?:?]
        at com.solodevelopment.tokens.commands.arguments.MenuArgument.request(MenuArgument.java:17) ~[?:?]
        at com.solodevelopment.tokens.commands.BaseCommand.onAdminCommand(BaseCommand.java:288) ~[?:?]
        at com.solodevelopment.tokens.commands.BaseCommand.execute(BaseCommand.java:64) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 14 more```

**Comment by ItzSave** [comment]
2.9.9 fixed the issue.
